export const contractsPackage = '@oneday/contracts';
export {
  CHANNEL_MENU_CATALOG,
  CIRCLE_MENU_CATALOG,
  EMPLOYEE_MENU_CATALOG,
  MANAGEMENT_MENU_CATALOG,
  MENU_GROUP_LABELS,
  PLATFORM_MENU_CATALOG,
  PLATFORM_PRODUCT_HOMES,
  STORE_MANAGER_MENU_ITEM,
  STORE_MANAGER_PACKAGE_ACTIONS,
  defaultHomeHref,
  filterMenuCatalog,
  groupMenuItems,
  menuCatalogFor,
  resolveAvailableProducts,
  resolveMenuProduct,
  resolvePlatformShellAccess,
  shellModeAllows,
  type MenuCatalogItem,
  type MenuDto,
  type MenuItemDto,
  type MenuNavGroup,
  type MenuProduct,
  type MenuProductLink,
  type MenuScopeDto,
  type PlatformShellMode,
} from './menu';
export {
  mergeNetworkScopes,
  mergeStoreScopes,
  networkListFilter,
  networkScopeAllows,
  networkWriteAllows,
  storeScopeAllows,
  storeWriteAllows,
  toMenuScope,
  type DataScopeRecord,
  type DataScopeType,
  type NetworkScopeType,
} from './data-scope';
